export const tarotQuestions = [
{ question: "¿Qué representa principalmente El Loco en el Tarot?", options: ["Cautela y miedo","Nuevos comienzos y libertad","Rutina estable","Castigo"], answer: 1 },
{ question: "¿Qué significa Dos de Bastos en un proyecto?", options: ["Duda permanente","Planificación y decisión de expansión","Cierre inmediato","Fracaso"], answer: 1 },
{ question: "¿Qué comunica Nueve de Oros + Reina de Oros conjuntamente?", options: ["Escasez","Independencia económica y disfrute de recursos","Inestabilidad","Debilidad"], answer: 1 },
{ question: "¿Qué indica Tres de Espadas invertido (si se considera inversión)?", options: ["Permanente dolor","Proceso de curación","Mayor ruptura","Estancamiento"], answer: 1 },
{ question: "¿Qué sugiere As de Copas + Dos de Copas?", options: ["Distancia emocional","Nuevo comienzo sentimental que evoluciona a unión","Pérdida","Ambigüedad"], answer: 1 },
{ question: "¿Qué comunica La Muerte + El Sol juntos?", options: ["Final trágico","Renovación exitosa y nueva vida","Estancamiento","Pobreza"], answer: 1 },
{ question: "¿Qué indica La Fuerza + La Justicia?", options: ["Conflicto sin fin","Coraje y equilibrio en decisiones justas","Descontrol","Caída"], answer: 1 },
{ question: "¿Qué sugiere El Juicio + El Mundo?", options: ["Olvido","Cumplimiento y reconocimiento global","Duda prolongada","Ruptura"], answer: 1 },
{ question: "¿Qué significa Caballero de Bastos + Ocho de Bastos?", options: ["Lentitud","Avance rápido y energía impulsiva","Estabilidad","Ruptura"], answer: 1 },
{ question: "¿Qué comunica Cinco de Oros + Seis de Bastos?", options: ["Éxito garantizado","Falsa apariencia de éxito tras pérdida","Plenitud","Desinterés"], answer: 1 },
{ question: "¿Qué indica As de Espadas + Reina de Espadas?", options: ["Silencio forzado","Verdad y comunicación clara con autoridad","Desorden emocional","Mala fe"], answer: 1 },
{ question: "¿Qué sugiere Siete de Copas + La Estrella?", options: ["Confusión sin salida","Inspiración que clarifica sueños","Pérdida de rumbo","Fracaso"], answer: 1 },
{ question: "¿Qué significa Dos de Copas + Tres de Copas juntos?", options: ["Ruptura social","Celebración de una relación y apoyo comunitario","Conflicto","Indiferencia"], answer: 1 },
{ question: "¿Qué comunica Cuatro de Oros en finanzas?", options: ["Generosidad extrema","Apego y retención de recursos","Flujo positivo","Inversión segura"], answer: 1 },
{ question: "¿Qué indica Ocho de Espadas + El Diablo juntos?", options: ["Liberación inmediata","Ataduras mentales y sensación de no poder salir","Alegría","Ruptura"], answer: 1 },
{ question: "¿Qué sugiere Nueve de Bastos + La Fuerza?", options: ["Rendición","Resistencia y coraje para seguir adelante","Desmoralización","Fracaso"], answer: 1 },
{ question: "¿Qué significa Tres de Bastos + As de Bastos?", options: ["Estancamiento creativo","Expansión con nueva oportunidad creativa","Retroceso","Confusión"], answer: 1 },
{ question: "¿Qué comunica La Sacerdotisa + El Ermitaño?", options: ["Distracción","Profundización espiritual y sabiduría interior","Caída","Desorden"], answer: 1 },
{ question: "¿Qué indica La Emperatriz + El Emperador juntos?", options: ["Conflicto eterno","Equilibrio entre nutrición y estructura","Desgaste","Inseguridad"], answer: 1 },
{ question: "¿Qué sugiere Dos de Espadas + La Justicia?", options: ["Decisión sin consecuencias","Necesidad de decisión informada y justa","Error irreversible","Caída"], answer: 1 },
{ question: "¿Qué significa As de Oros + Ocho de Oros?", options: ["Descuido","Nueva oportunidad material y trabajo dedicado","Pérdida","Estancamiento"], answer: 1 },
{ question: "¿Qué comunica Diez de Copas + El Mundo?", options: ["Pérdida familiar","Culminación de felicidad familiar y logro global","Ruptura doméstica","Confusión"], answer: 1 },
{ question: "¿Qué indica cuando aparecen muchas espadas en una lectura?", options: ["Paz mental","Conflictos, pensamiento y desafíos mentales","Abundancia material","Celebración"], answer: 1 },
{ question: "¿Qué sugiere aparición de muchos bastos?", options: ["Inercia","Acción, energía y movimiento","Estancamiento","Ruina"], answer: 1 },
{ question: "¿Qué comunica aparición de muchas copas?", options: ["Riesgo financiero","Emociones intensas y relaciones","Choque físico","Desorden legal"], answer: 1 },
{ question: "¿Qué indica aparición de muchos oros (pentáculos)?", options: ["Falta de recursos","Enfoque en lo material y lo práctico","Desánimo","Alegría"], answer: 1 },
{ question: "¿Qué sugiere que el Rey de Copas y la Reina de Copas aparezcan juntos?", options: ["Conflicto","Madurez emocional en pareja o liderazgo emocional","Pérdida","Desconfianza"], answer: 1 },
{ question: "¿Qué significa si aparecen El Loco, El Mago y El Sol juntos?", options: ["Derrota total","Comienzo feliz con poder personal y éxito","Confusión profunda","Ruptura"], answer: 1 },
{ question: "¿Qué comunica combinación de La Torre + Diez de Espadas?", options: ["Mejora inmediata","Colapso y final doloroso antes de reconstrucción","Estabilidad","Triunfo"], answer: 1 }];
