const tarotQuestions = [
    { q: "¿Qué representa El Loco en el Tarot?", options: ["Inicios y libertad", "Estabilidad", "Control", "Fracaso"], answer: 0 },
    { q: "¿Qué elemento se asocia con los Bastos?", options: ["Fuego", "Aire", "Agua", "Tierra"], answer: 0 },
    { q: "¿Qué elemento se asocia con las Copas?", options: ["Agua", "Aire", "Fuego", "Tierra"], answer: 0 },
    { q: "¿Qué elemento se asocia con las Espadas?", options: ["Aire", "Fuego", "Agua", "Tierra"], answer: 0 },
    { q: "¿Qué elemento se asocia con los Oros?", options: ["Tierra", "Fuego", "Agua", "Aire"], answer: 0 },

    { q: "¿Qué representa El Mago?", options: ["Manifestación", "Confusión", "Derrota", "Oscuridad"], answer: 0 },
    { q: "¿Qué representa La Sacerdotisa?", options: ["Intuición", "Acción impulsiva", "Riesgo", "Agresión"], answer: 0 },
    { q: "¿Qué representa La Emperatriz?", options: ["Abundancia", "Soledad", "Conflicto", "Aislamiento"], answer: 0 },
    { q: "¿Qué representa El Emperador?", options: ["Autoridad", "Desorganización", "Sueños", "Descontrol"], answer: 0 },
    { q: "¿Qué representa El Papa?", options: ["Guía espiritual", "Locura", "Egoísmo", "Perdida"], answer: 0 },

    { q: "¿Qué representa Los Enamorados?", options: ["Decisiones", "Fracaso sentimental", "Soledad", "Caos"], answer: 0 },
    { q: "¿Qué representa El Carro?", options: ["Avance", "Estancamiento", "Ilusión", "Miedo"], answer: 0 },

    { q: "¿Qué representa La Justicia?", options: ["Equilibrio", "Exceso", "Pasión", "Fantasia"], answer: 0 },
    { q: "¿Qué representa El Ermitaño?", options: ["Sabiduría interior", "Caos", "Guerra", "Oscuridad"], answer: 0 },
    { q: "¿Qué representa La Rueda de la Fortuna?", options: ["Cambio", "Derrota", "Estabilidad", "Engaño"], answer: 0 },
    { q: "¿Qué representa La Fuerza?", options: ["Dominio interno", "Violencia", "Derrota", "Locura"], answer: 0 },

    { q: "¿Qué representa El Colgado?", options: ["Pausa y perspectiva", "Acción inmediata", "Violencia", "Destrucción"], answer: 0 },
    { q: "¿Qué representa La Muerte?", options: ["Transformación", "Muerte literal", "Oscuridad total", "Riqueza inmediata"], answer: 0 },
    { q: "¿Qué representa La Templanza?", options: ["Equilibrio interno", "Ataque", "Aventura", "Soledad"], answer: 0 },
    { q: "¿Qué representa El Diablo?", options: ["Apegos", "Libertad inmediata", "Pureza", "Intuición"], answer: 0 },
    { q: "¿Qué representa La Torre?", options: ["Ruptura", "Abundancia", "Estabilidad", "Relax"], answer: 0 },

    { q: "¿Qué representa La Estrella?", options: ["Esperanza", "Oscuridad", "Peligro", "Manipulación"], answer: 0 },
    { q: "¿Qué representa La Luna?", options: ["Confusión e intuición", "Claridad", "Éxito", "Amor estable"], answer: 0 },
    { q: "¿Qué representa El Sol?", options: ["Éxito y alegría", "Oscuridad", "Aislamiento", "Engaño"], answer: 0 },
    { q: "¿Qué representa El Juicio?", options: ["Renacimiento", "Oscuridad", "Caída", "Confusión"], answer: 0 },
    { q: "¿Qué representa El Mundo?", options: ["Culminación", "Fracaso", "Estancamiento", "Soledad"], answer: 0 },

    { q: "¿Qué indica el As de Copas?", options: ["Nuevos sentimientos", "Conflicto", "Estancamiento", "Soledad"], answer: 0 },
    { q: "¿Qué indica el As de Espadas?", options: ["Claridad mental", "Sueños", "Oscuridad", "Estancamiento"], answer: 0 },
    { q: "¿Qué indica el As de Bastos?", options: ["Inicio creativo", "Derrota", "Soledad", "Confusión"], answer: 0 },
    { q: "¿Qué indica el As de Oros?", options: ["Oportunidad material", "Perdida", "Miedo", "Aislamiento"], answer: 0 },

    { q: "¿Qué significa el Dos de Copas?", options: ["Unión emocional", "División", "Miedo", "Desorden"], answer: 0 },
    { q: "¿Qué indica el Tres de Oros?", options: ["Trabajo en equipo", "Caos", "Soledad", "Derrota"], answer: 0 },
    { q: "¿Qué indica el Cuatro de Espadas?", options: ["Descanso", "Ataque", "Movimiento", "Fiesta"], answer: 0 },
    { q: "¿Qué indica el Cinco de Bastos?", options: ["Conflicto", "Armonía", "Paz", "Amor"], answer: 0 },

    { q: "¿Qué indica el Seis de Copas?", options: ["Nostalgia", "Violencia", "Miedo", "Soledad"], answer: 0 },
    { q: "¿Qué indica el Siete de Espadas?", options: ["Engaño", "Sinceridad", "Éxito", "Pasión"], answer: 0 },
    { q: "¿Qué indica el Ocho de Bastos?", options: ["Movimiento rápido", "Estancamiento", "Miedo", "Soledad"], answer: 0 },
    { q: "¿Qué indica el Nueve de Oros?", options: ["Independencia", "Pérdida", "Caída", "Soledad"], answer: 0 },
    { q: "¿Qué indica el Diez de Copas?", options: ["Armonía familiar", "Conflicto", "Oscuridad", "Soledad"], answer: 0 },

    { q: "¿Qué indica el Sota de Espadas?", options: ["Vigilancia", "Sueño", "Pasividad", "Riesgo"], answer: 0 },
    { q: "¿Qué indica el Caballero de Bastos?", options: ["Impulso", "Miedo", "Estancamiento", "Oscuridad"], answer: 0 },
    { q: "¿Qué indica la Reina de Copas?", options: ["Intuición profunda", "Frialdad", "Oscuridad", "Caos"], answer: 0 },
    { q: "¿Qué indica el Rey de Oros?", options: ["Estabilidad material", "Confusión", "Locura", "Derrota"], answer: 0 },

    { q: "¿Qué carta indica traición?", options: ["Diez de Espadas", "Tres de Copas", "El Sol", "Rey de Bastos"], answer: 0 },
    { q: "¿Qué carta indica celebración?", options: ["Tres de Copas", "Ocho de Espadas", "La Torre", "El Diablo"], answer: 0 },

    { q: "¿Qué carta indica ilusión o autoengaño?", options: ["Siete de Copas", "As de Espadas", "El Mundo", "Dos de Oros"], answer: 0 },
    { q: "¿Qué carta representa duelo?", options: ["Cinco de Copas", "Diez de Oros", "As de Bastos", "Tres de Espadas"], answer: 0 },
    { q: "¿Qué carta indica tristeza profunda?", options: ["Tres de Espadas", "Nueve de Copas", "El Sol", "La Estrella"], answer: 0 },

    { q: "¿Qué carta representa ansiedad y pesadillas?", options: ["Nueve de Espadas", "As de Oros", "Rey de Bastos", "Tres de Oros"], answer: 0 },
    { q: "¿Qué carta sugiere cargas y exceso de responsabilidades?", options: ["Diez de Bastos", "Dos de Copas", "El Loco", "El Carro"], answer: 0 },
    { q: "¿Qué carta indica bloqueo emocional?", options: ["Dos de Espadas", "Cuatro de Oros", "As de Oros", "Cinco de Bastos"], answer: 0 },

    { q: "¿Qué carta muestra victoria y éxito público?", options: ["Seis de Bastos", "Cuatro de Copas", "Nueve de Espadas", "La Luna"], answer: 0 },
    { q: "¿Qué carta indica opciones múltiples y fantasías?", options: ["Siete de Copas", "Dos de Bastos", "El Papa", "La Justicia"], answer: 0 },

    { q: "¿Qué carta indica egoísmo y retención excesiva?", options: ["Cuatro de Oros", "Nueve de Oros", "Siete de Bastos", "La Templanza"], answer: 0 },
    { q: "¿Qué carta indica equilibrio precario y decisiones rápidas?", options: ["Dos de Oros", "Tres de Espadas", "El Mundo", "As de Copas"], answer: 0 },

    { q: "¿Qué carta habla de confusión emocional y apatía?", options: ["Cuatro de Copas", "El Carro", "El Sol", "As de Espadas"], answer: 0 },
    { q: "¿Qué carta indica defensa y resistencia?", options: ["Siete de Bastos", "Seis de Espadas", "Reina de Copas", "As de Oros"], answer: 0 },

    { q: "¿Qué carta representa viajes o transición?", options: ["Seis de Espadas", "Tres de Copas", "Dos de Bastos", "Rey de Oros"], answer: 0 },
    { q: "¿Qué carta representa un final doloroso?", options: ["Diez de Espadas", "Diez de Copas", "El Sol", "El Mago"], answer: 0 },
    { q: "¿Qué carta representa esperanza renovada?", options: ["La Estrella", "El Diablo", "La Torre", "Ocho de Espadas"], answer: 0 },

    { q: "¿Qué carta indica manipulación emocional?", options: ["Rey de Copas invertido", "Seis de Oros", "As de Bastos", "El Mundo"], answer: 0 },
    { q: "¿Qué carta indica celos o control?", options: ["Rey de Bastos invertido", "As de Espadas", "El Carro", "La Emperatriz"], answer: 0 },
    { q: "¿Qué carta indica un amor idealizado?", options: ["La Estrella", "El Diablo", "Tres de Espadas", "Siete de Espadas"], answer: 0 },

    { q: "¿Qué arcano representa introspección profunda?", options: ["El Ermitaño", "La Fuerza", "El Sol", "El Juicio"], answer: 0 },
    { q: "¿Qué arcano habla de engaños y sombras?", options: ["La Luna", "El Sol", "La Rueda", "El Mago"], answer: 0 },
    { q: "¿Qué arcano indica revelación y claridad?", options: ["El Sol", "El Diablo", "La Torre", "El Colgado"], answer: 0 },

    { q: "¿Qué arcano señala una elección difícil?", options: ["Los Enamorados", "El Papa", "La Justicia", "El Mundo"], answer: 0 },
    { q: "¿Qué arcano muestra destrucción necesaria?", options: ["La Torre", "El Sol", "El Mago", "El Carro"], answer: 0 },
    { q: "¿Qué arcano simboliza renacimiento?", options: ["El Juicio", "El Diablo", "El Papa", "El Colgado"], answer: 0 },

    { q: "¿Qué arcano mayor indica estabilidad máxima?", options: ["El Emperador", "El Loco", "La Sacerdotisa", "El Carro"], answer: 0 },
    { q: "¿Qué arcano mayor simboliza sabiduría femenina oculta?", options: ["La Sacerdotisa", "La Estrella", "La Fuerza", "El Mundo"], answer: 0 },
    { q: "¿Qué arcano mayor indica abundancia fértil?", options: ["La Emperatriz", "La Muerte", "El Papa", "La Templanza"], answer: 0 },

    { q: "¿Qué carta menor simboliza sanación y unión?", options: ["Dos de Copas", "Tres de Espadas", "Cinco de Copas", "Ocho de Oros"], answer: 0 },
    { q: "¿Qué carta menor representa aprendizaje constante?", options: ["Ocho de Oros", "Diez de Copas", "Sota de Copas", "Tres de Bastos"], answer: 0 },

    { q: "¿Qué carta menor indica espera y planeación?", options: ["Tres de Bastos", "Cinco de Bastos", "Diez de Espadas", "Rey de Copas"], answer: 0 },
    { q: "¿Qué carta menor indica avance determinado?", options: ["El Carro", "Ocho de Espadas", "La Luna", "Tres de Oros"], answer: 0 },

    { q: "¿Qué carta menor indica recuperación emocional?", options: ["Seis de Espadas", "Nueve de Espadas", "Cinco de Copas", "Ocho de Oros"], answer: 0 },
{ q: "En una lectura sobre decisiones complejas, ¿qué matiz menos evidente puede señalar El Loco?", options: ["La necesidad de confiar en un impulso que parece irracional pero es intuitivo", "Un riesgo perfectamente calculado", "Una vía claramente equivocada", "Una revelación externa inevitable"], answer: 0 },
{ q: "Cuando El Mago aparece en contexto laboral, ¿qué lectura sutil puede sugerir?", options: ["Habilidad desaprovechada por exceso de distracciones disfrazadas de productividad", "Una promoción inmediata", "Una caída profesional inevitable", "Un periodo pasivo y sin impacto"], answer: 0 },
{ q: "¿Qué interpretación no tan obvia puede ofrecer La Sacerdotisa en un conflicto emocional?", options: ["Información que solo se revela cuando el consultante deja de intentar controlarla", "Una verdad expuesta directamente", "Una ruptura contundente", "Un engaño sin consecuencias"], answer: 0 },
{ q: "La Emperatriz suele indicar abundancia, pero ¿qué matiz complejo puede señalar en relaciones?", options: ["Una conexión fértil que exige reciprocidad emocional madura", "Un romance efímero", "Una unión sin retos", "Una distancia imposible de reparar"], answer: 0 },
{ q: "El Emperador puede representar estabilidad, pero ¿qué advertencia más profunda oculta?", options: ["Estructuras tan rígidas que impiden la adaptación ante cambios necesarios", "Autoridad flexible", "Caos total", "Sumisión absoluta sin matices"], answer: 0 },
{ q: "En un proceso espiritual, ¿qué lectura menos evidente puede señalar El Papa?", options: ["Un aprendizaje que proviene de una fuente conservadora inesperadamente valiosa", "Una rebeldía obligatoria", "Un quiebre de fe definitivo", "Una búsqueda emocional impulsiva"], answer: 0 },
{ q: "¿Qué interpretación sutil pueden aportar Los Enamorados en decisiones morales?", options: ["Una elección que debe alinearse con principios internos más que con deseos inmediatos", "Una unión indiscutible", "Una separación brusca", "Una obligación impuesta por terceros"], answer: 0 },
{ q: "El Carro simboliza avance, pero ¿qué aspecto más complejo puede revelar?", options: ["Un progreso que depende del dominio emocional más que de la acción física", "Un viaje literal", "Un bloqueo permanente", "Un cambio material garantizado"], answer: 0 },
{ q: "En disputas legales, ¿qué interpretación menos evidente trae La Justicia?", options: ["Una resolución que será neutral pero obligará al consultante a asumir mayor responsabilidad", "Un favoritismo claro", "Una injusticia absoluta", "Una decisión impulsiva"], answer: 0 },
{ q: "El Ermitaño suele representar introspección, pero ¿qué matiz complejo puede sugerir profesionalmente?", options: ["Retirada estratégica para observar dinámicas ocultas antes de actuar", "Renuncia inevitable", "Ascenso espontáneo", "Inacción definitiva"], answer: 0 },
{ q: "La Rueda de la Fortuna puede indicar cambios, pero ¿qué lectura menos evidente sugiere?", options: ["Ciclos que se repiten porque el consultante aún no ha integrado un aprendizaje pendiente", "Un golpe de suerte inmediato", "Un fracaso seguro", "Un cambio sin propósito"], answer: 0 },
{ q: "La Fuerza parece positiva, pero ¿qué matiz psicológico difícil insinúa?", options: ["Control emocional que requiere enfrentar impulsos reprimidos", "Agresión inevitable", "Resignación pasiva", "Confianza plena sin esfuerzo"], answer: 0 },
{ q: "¿Qué lectura menos obvia puede tener El Colgado en temas de propósito personal?", options: ["Una pausa que revela un valor oculto solo si el consultante abandona expectativas rígidas", "Un sacrificio inútil", "Una decisión impulsiva", "Un cambio drástico accidental"], answer: 0 },
{ q: "La Muerte señala transformación, pero ¿qué matiz sutil puede sugerir?", options: ["Un cierre emocional que libera energía creativa reprimida", "Destrucción total", "Un vacío sin recuperación", "Una repetición del pasado"], answer: 0 },
{ q: "La Templanza suele ser armonía, pero ¿qué lectura más compleja encierra?", options: ["Integrar polaridades opuestas que el consultante ha negado", "Evitar conflictos", "Aceptar injusticias", "Bloquear emociones"], answer: 0 },
{ q: "¿Qué significado oculto puede tener El Diablo en temas económicos?", options: ["Ataduras creadas por hábitos que dan sensación de seguridad pero restringen el crecimiento", "Pérdida inmediata", "Libertad absoluta", "Una ganancia segura"], answer: 0 },
{ q: "La Torre indica ruptura, pero ¿qué lectura sutil puede aportar?", options: ["Una verdad que derriba ilusiones necesarias para avanzar", "Un fracaso garantizado", "Un conflicto menor", "Una pausa trivial"], answer: 0 },
{ q: "¿Qué matiz menos evidente puede mostrar La Estrella en temas de sanación emocional?", options: ["Esperanza que requiere vulnerabilidad consciente", "Optimismo ingenuo", "Negación de la realidad", "Curación automática"], answer: 0 },
{ q: "La Luna suele ser confusión, pero ¿qué interpretación compleja agrega?", options: ["Temores que actúan como guía simbólica si se interpretan correctamente", "Mentiras externas", "Una certeza absoluta", "Una decisión firme"], answer: 0 },
{ q: "El Sol representa claridad, pero ¿qué matiz difícil puede implicar?", options: ["Visibilidad que obliga al consultante a asumir responsabilidades evitadas", "Éxito sin esfuerzo", "Un fracaso oculto", "Un cambio negativo"], answer: 0 },
{ q: "¿Qué lectura profunda puede aportar El Juicio en procesos personales?", options: ["Un llamado interno que surge tras reconocer patrones inconclusos", "Un final definitivo", "Una decisión ajena", "Una revelación accidental"], answer: 0 },
{ q: "El Mundo indica culminación, pero ¿qué dimensión menos obvia agrega?", options: ["La necesidad de integrar logros antes de iniciar un nuevo ciclo", "Un cierre inmodificable", "Un retroceso seguro", "Un conflicto inevitable"], answer: 0 },
{ q: "El As de Oros puede indicar oportunidad, pero ¿qué lectura más sutil implica?", options: ["Potencial material que depende de una reorganización interna", "Ganancia inmediata", "Pérdida asegurada", "Un ciclo estancado"], answer: 0 },
{ q: "En decisiones prácticas, ¿qué representa el Dos de Oros en su lectura más compleja?", options: ["Adaptación que oculta desgaste acumulado", "Fracaso", "Una elección obvia", "Control absoluto"], answer: 0 },
{ q: "¿Qué matiz menos evidente aporta el Tres de Oros en trabajos colaborativos?", options: ["Reconocimiento que depende de la capacidad de aceptar guía", "Conflictos inevitables", "Soledad profesional", "Desacuerdo irreparable"], answer: 0 },
{ q: "El Cuatro de Oros puede hablar de control, pero ¿qué interpretación profunda sugiere?", options: ["Protección emocional derivada de experiencias pasadas no resueltas", "Generosidad excesiva", "Ausencia de límites", "Desinterés económico"], answer: 0 },
{ q: "El Cinco de Oros puede ser dificultad, pero ¿qué matiz complejo revela?", options: ["Carencia percibida más que real, alimentada por miedo interno", "Abundancia inmediata", "Riqueza súbita", "Éxito seguro"], answer: 0 },
{ q: "El Seis de Oros habla de dar y recibir, pero ¿qué lectura sutil aporta?", options: ["Desequilibrio camuflado como generosidad", "Carencia total", "Manipulación evidente", "Indiferencia emocional"], answer: 0 },
{ q: "El Siete de Oros indica espera, pero ¿qué matiz psicológico profundo contiene?", options: ["Evaluación que puede revelar miedo al siguiente paso", "Inacción definitiva", "Desesperación", "Abandono"], answer: 0 },
{ q: "El Ocho de Oros es dedicación, pero ¿qué interpretación sutil ofrece?", options: ["Una mejora que requiere abandonar perfeccionismo", "Pereza", "Caos", "Distracción crónica"], answer: 0 },
{ q: "El Nueve de Oros puede hablar de independencia, pero ¿qué matiz complejo sugiere?", options: ["Autosuficiencia que oculta dificultad para pedir apoyo", "Dependencia total", "Éxito falso", "Mentira evidente"], answer: 0 },
{ q: "El Diez de Oros simboliza estabilidad, pero ¿qué lectura menos evidente aporta?", options: ["Seguridad basada en tradiciones que requieren reinterpretación", "Riesgo extremo", "Soledad", "Pérdida total"], answer: 0 },
{ q: "¿Qué lectura profunda puede tener el As de Copas en vínculos nuevos?", options: ["Apertura emocional que exige revisar viejas heridas", "Ilusión sin base", "Fin inmediato", "Distancia emocional"], answer: 0 },
{ q: "El Dos de Copas indica unión, pero ¿qué matiz menos obvio incluye?", options: ["Reconocimiento mutuo que solo florece con vulnerabilidad consciente", "Conflictos inevitables", "Engaño", "Ruptura rápida"], answer: 0 },
{ q: "El Tres de Copas es celebración, pero ¿qué lectura más compleja añade?", options: ["Apoyo emocional que requiere equilibrio para evitar dependencia", "Soledad", "Distancia", "Rechazo social"], answer: 0 },
{ q: "¿Qué lectura sutil puede tener el Cuatro de Copas en rutinas emocionales?", options: ["Insatisfacción que surge por expectativas rígidas más que por falta real", "Alegría segura", "Descontrol", "Euforia"], answer: 0 },
{ q: "El Cinco de Copas indica pérdida, pero ¿qué matiz psicológico revela?", options: ["Dolor que persiste por apego a una interpretación antigua del pasado", "Triunfo", "Amor pleno", "Riqueza"], answer: 0 },
{ q: "El Seis de Copas puede mostrar nostalgia, pero ¿qué lectura profunda agrega?", options: ["Idealización que distorsiona decisiones presentes", "Cambios bruscos", "Olvido total", "Confusión"], answer: 0 },
{ q: "El Siete de Copas indica opciones, pero ¿qué matiz complejo ofrece?", options: ["Deseos que reflejan aspectos internos no integrados", "Claridad absoluta", "Certeza", "Soledad"], answer: 0 },
{ q: "¿Qué lectura menos obvia puede tener el Ocho de Copas?", options: ["Retiro que nace de un reconocimiento profundo y silencioso", "Estancamiento", "Éxito fácil", "Euforia inmediata"], answer: 0 },
{ q: "El Nueve de Copas es satisfacción, pero ¿qué interpretación más compleja contiene?", options: ["Logro que depende de aceptar límites personales", "Fracaso", "Desilusión", "Conflicto"], answer: 0 },
{ q: "El Diez de Copas señala armonía, pero ¿qué matiz oculto puede mostrar?", options: ["Felicidad que requiere permitir imperfecciones", "Caos", "Soledad", "Desunión"], answer: 0 },
{ q: "¿Qué significado profundo tiene el As de Espadas en revelaciones importantes?", options: ["Claridad que puede resultar incómoda pero liberadora", "Oscuridad", "Mentira", "Confusión total"], answer: 0 },
{ q: "El Dos de Espadas indica indecisión, ¿qué matiz psicológico añade?", options: ["Negación activa disfrazada de balance", "Ataque", "Violencia", "Certeza"], answer: 0 },
{ q: "El Tres de Espadas muestra dolor, pero ¿qué lectura compleja sugiere?", options: ["Liberación emocional que emerge tras aceptar la herida", "Paz", "Unión", "Armonía total"], answer: 0 },
{ q: "El Cuatro de Espadas es descanso, pero ¿qué interpretación profunda agrega?", options: ["Una pausa necesaria para reorganizar creencias", "Acción rápida", "Caos", "Explosión emocional"], answer: 0 },
{ q: "El Cinco de Espadas habla de conflicto, pero ¿qué matiz menos evidente incluye?", options: ["Victoria que deja vacíos internos no reconocidos", "Armonía", "Celebración", "Calma"], answer: 0 },
{ q: "El Seis de Espadas indica transición, pero ¿qué lectura sutil aporta?", options: ["Un movimiento emocional más interno que externo", "Derrota", "Estancamiento", "Caos"], answer: 0 },
{ q: "¿Qué interpretación compleja tiene el Siete de Espadas?", options: ["Estrategia nacida del miedo a la vulnerabilidad", "Amistad", "Generosidad", "Claridad"], answer: 0 },
{ q: "El Ocho de Espadas muestra limitación, pero ¿qué matiz profundo sugiere?", options: ["Restricciones autoimpuestas por creencias antiguas", "Libertad total", "Éxito inmediato", "Alegría"], answer: 0 },
{ q: "El Nueve de Espadas indica ansiedad, pero ¿qué lectura interna agrega?", options: ["Pensamientos que amplifican miedos irreales", "Riqueza", "Éxito", "Relajación"], answer: 0 },
{ q: "El Diez de Espadas representa final, pero ¿qué matiz menos obvio incluye?", options: ["Cierre que permite reconstrucción total", "Diversión", "Duda", "Éxito"], answer: 0 },
{ q: "El As de Bastos es inicio creativo, pero ¿qué lectura profunda puede aportar?", options: ["Inspiración que exige superar miedo al fracaso", "Cansancio", "Oscuridad", "Ruido"], answer: 0 },
{ q: "El Dos de Bastos indica visión, pero ¿qué matiz complejo agrega?", options: ["Planificar sin actuar por temor al riesgo", "Desorden", "Impulso", "Miedo irracional"], answer: 0 },
{ q: "El Tres de Bastos habla de expansión, pero ¿qué lectura menos evidente da?", options: ["Crecimiento dependiente de abandonar expectativas rígidas", "Retroceso", "Estancamiento", "Caída"], answer: 0 },
{ q: "El Cuatro de Bastos es celebración, pero ¿qué significado más profundo puede contener?", options: ["Estabilidad que nace de colaboración sincera", "Soledad", "Fracaso", "Distancia"], answer: 0 },
{ q: "¿Qué lectura compleja aporta el Cinco de Bastos en conflictos sociales?", options: ["Competencia que revela habilidades ocultas", "Paz", "Silencio", "Unión"], answer: 0 },
{ q: "El Seis de Bastos es victoria, pero ¿qué matiz psicológico incluye?", options: ["Reconocimiento que puede generar presión interna", "Derrota", "Caída", "Fracaso"], answer: 0 },
{ q: "El Siete de Bastos habla de defensa, pero ¿qué lectura sutil puede aportar?", options: ["Protección que surge de experiencias previas no resueltas", "Renuncia", "Éxito fácil", "Calma total"], answer: 0 },
{ q: "El Ocho de Bastos indica movimiento, pero ¿qué significado profundo puede tener?", options: ["Aceleración que exige claridad de intención", "Estancamiento", "Cansancio", "Rutina"], answer: 0 },
{ q: "El Nueve de Bastos es resistencia, pero ¿qué lectura compleja da?", options: ["Persistencia nacida de miedo a repetir una caída pasada", "Entrega", "Fracaso", "Inacción"], answer: 0 },
{ q: "El Diez de Bastos indica carga, pero ¿qué matiz psicológico profundo incluye?", options: ["Responsabilidades asumidas por deseo de aprobación", "Libertad total", "Alegría", "Nada significativo"], answer: 0 },
{ q: "¿Qué lectura menos evidente tiene el Paje de Oros en procesos de aprendizaje?", options: ["Disciplina que surge de curiosidad auténtica", "Caos", "Mentira", "Desorden"], answer: 0 },
{ q: "El Caballero de Oros indica constancia, pero ¿qué matiz profundo implica?", options: ["Persistencia que puede convertirse en rigidez", "Impulso", "Desorden", "Velocidad extrema"], answer: 0 },
{ q: "La Reina de Oros suele ser nutritiva, pero ¿qué complejidad añade?", options: ["Cuidado que puede ocultar necesidad de control", "Egoísmo", "Frialdad", "Desconexión"], answer: 0 },
{ q: "El Rey de Oros indica estabilidad, pero ¿qué matiz sutil aporta?", options: ["Seguridad lograda tras superar miedo a la vulnerabilidad material", "Caos", "Derrota", "Engaño"], answer: 0 },
{ q: "El Paje de Copas simboliza sensibilidad, pero ¿qué interpretación profunda tiene?", options: ["Intuición emergente que aún requiere madurez emocional", "Dureza", "Rabia", "Confusión"], answer: 0 },
{ q: "El Caballero de Copas indica romanticismo, pero ¿qué lectura sutil agrega?", options: ["Búsqueda idealista que puede ocultar temor a la intimidad", "Conflicto", "Ego", "Rencor"], answer: 0 },
{ q: "La Reina de Copas muestra compasión, pero ¿qué matiz complejo incluye?", options: ["Empatía que puede llevar al agotamiento emocional", "Frialdad", "Mentira", "Impulso"], answer: 0 },
{ q: "El Rey de Copas es equilibrio, pero ¿qué lectura profunda aporta?", options: ["Control emocional adquirido tras enfrentar inseguridades internas", "Furia", "Descontrol", "Negación"], answer: 0 },
{ q: "El Paje de Espadas señala ideas nuevas, pero ¿qué matiz menos evidente tiene?", options: ["Curiosidad mental que nace de una inquietud latente", "Cansancio", "Oscuridad", "Rutina"], answer: 0 },
{ q: "El Caballero de Espadas indica acción rápida, pero ¿qué interpretación compleja sugiere?", options: ["Impulso intelectual que puede pasar por encima de emociones necesarias", "Falta de acción", "Duda", "Quietud"], answer: 0 },
{ q: "La Reina de Espadas representa claridad, pero ¿qué matiz sutil puede revelar?", options: ["Lógica desarrollada tras dolor emocional profundo", "Ego", "Mentira", "Sometimiento"], answer: 0 },
{ q: "El Rey de Espadas simboliza razón, pero ¿qué lectura profunda incluye?", options: ["Discernimiento que exige desapego consciente", "Fantasía", "Emoción", "Caos"], answer: 0 },
{ q: "El Paje de Bastos muestra entusiasmo, pero ¿qué lectura menos obvia ofrece?", options: ["Impulso creativo que puede dispersarse sin dirección", "Tristeza", "Pesadez", "Rutina"], answer: 0 },
{ q: "El Caballero de Bastos indica aventura, pero ¿qué matiz complejo aporta?", options: ["Búsqueda constante que puede ocultar miedo al compromiso", "Estancamiento", "Soledad", "Nada significativo"], answer: 0 },
{ q: "La Reina de Bastos es confianza, pero ¿qué lectura sutil revela?", options: ["Seguridad que nace de integrar vulnerabilidad", "Temor", "Desorden", "Aislamiento"], answer: 0 },
{ q: "El Rey de Bastos representa liderazgo, pero ¿qué matiz profundo implica?", options: ["Dirección firme que requiere moderar impulsividad interna", "Renuncia", "Oscuridad", "Mentira"], answer: 0 }
];

