export const astrologyQuestions = [{ question: "¿Qué representa el signo Aries en astrología?", options: ["Inicio y energía", "Estabilidad", "Comunicación", "Transformación"], answer: 0 },
{ question: "¿Cuál es el planeta regente de Tauro?", options: ["Marte", "Venus", "Mercurio", "Saturno"], answer: 1 },
{ question: "¿Qué elemento corresponde a Géminis?", options: ["Tierra", "Aire", "Fuego", "Agua"], answer: 1 },
{ question: "¿Cuál es el hogar zodiacal de la Luna?", options: ["Leo", "Cáncer", "Virgo", "Libra"], answer: 1 },
{ question: "¿Qué signo es conocido por ser perfeccionista?", options: ["Virgo", "Sagitario", "Aries", "Piscis"], answer: 0 },
{ question: "¿Cuál es el planeta regente de Leo?", options: ["El Sol", "La Luna", "Marte", "Urano"], answer: 0 },
{ question: "¿Qué elemento rige a Cáncer?", options: ["Agua", "Fuego", "Aire", "Tierra"], answer: 0 },
{ question: "¿Qué signo es conocido por buscar equilibrio y justicia?", options: ["Acuario", "Libra", "Aries", "Escorpio"], answer: 1 },
{ question: "¿Cuál es el regente tradicional de Escorpio?", options: ["Plutón", "Marte", "Saturno", "Urano"], answer: 1 },
{ question: "¿Qué signo está asociado a la exploración y la expansión?", options: ["Virgo", "Sagitario", "Capricornio", "Géminis"], answer: 1 },
{ question: "¿Qué planeta rige a Capricornio?", options: ["Saturno", "Júpiter", "Venus", "Mercurio"], answer: 0 },
{ question: "¿Qué signo es conocido por su originalidad e innovación?", options: ["Leo", "Tauro", "Acuario", "Escorpio"], answer: 2 },
{ question: "¿Qué planeta rige a Piscis?", options: ["Neptuno", "Venus", "Urano", "Marte"], answer: 0 },
{ question: "¿Cuál es el elemento dominante de Aries?", options: ["Aire", "Fuego", "Tierra", "Agua"], answer: 1 },
{ question: "¿Qué signo es conocido por su terquedad?", options: ["Cáncer", "Tauro", "Libra", "Sagitario"], answer: 1 },
{ question: "¿Cuál es el signo más comunicativo del zodiaco?", options: ["Géminis", "Escorpio", "Piscis", "Capricornio"], answer: 0 },
{ question: "¿Qué signo se asocia con el servicio y la salud?", options: ["Libra", "Aries", "Virgo", "Leo"], answer: 2 },
{ question: "¿Cuál es el signo más emocional del elemento agua?", options: ["Escorpio", "Cáncer", "Piscis", "Acuario"], answer: 1 },
{ question: "¿Cuál es el planeta regente de Géminis?", options: ["Mercurio", "Venus", "Marte", "Saturno"], answer: 0 },
{ question: "¿Qué signo representa al maestro del zodiaco?", options: ["Acuario", "Capricornio", "Sagitario", "Aries"], answer: 2 },
{ question: "¿Qué planeta rige a Leo?", options: ["Júpiter", "El Sol", "Saturno", "Urano"], answer: 1 },
{ question: "¿Qué signo es considerado el más intuitivo?", options: ["Acuario", "Piscis", "Capricornio", "Virgo"], answer: 1 },
{ question: "¿Qué elemento representa a Libra?", options: ["Agua", "Aire", "Tierra", "Fuego"], answer: 1 },
{ question: "¿Qué signo es conocido por su intensidad?", options: ["Escorpio", "Tauro", "Libra", "Géminis"], answer: 0 },
{ question: "¿Cuál es el planeta de la expansión?", options: ["Júpiter", "Marte", "Venus", "Saturno"], answer: 0 },
{ question: "¿Qué signo rige las estructuras y la disciplina?", options: ["Aries", "Capricornio", "Leo", "Cáncer"], answer: 1 },
{ question: "¿Qué planeta es conocido como el innovador?", options: ["Urano", "Plutón", "Venus", "Mercurio"], answer: 0 },
{ question: "¿Qué signo representa la espiritualidad profunda?", options: ["Géminis", "Piscis", "Virgo", "Escorpio"], answer: 1 },
{ question: "¿Cuál es el elemento de Sagitario?", options: ["Fuego", "Agua", "Aire", "Tierra"], answer: 0 },
{ question: "¿Qué signo está asociado con la responsabilidad?", options: ["Capricornio", "Leo", "Acuario", "Piscis"], answer: 0 },
{ question: "¿Qué signo se asocia con la libertad e independencia?", options: ["Géminis", "Acuario", "Libra", "Escorpio"], answer: 1 },
{ question: "¿Qué signo representa el renacimiento?", options: ["Cáncer", "Escorpio", "Virgo", "Piscis"], answer: 1 },
{ question: "¿Qué casa rige la comunicación?", options: ["Casa 1", "Casa 3", "Casa 5", "Casa 7"], answer: 1 },
{ question: "¿Qué casa rige las relaciones?", options: ["Casa 7", "Casa 2", "Casa 9", "Casa 11"], answer: 0 },
{ question: "¿Qué casa rige el trabajo y la salud?", options: ["Casa 4", "Casa 6", "Casa 8", "Casa 10"], answer: 1 },
{ question: "¿Qué casa rige la carrera y el éxito público?", options: ["Casa 7", "Casa 10", "Casa 2", "Casa 5"], answer: 1 },
{ question: "¿Qué casa rige los viajes largos y la filosofía?", options: ["Casa 3", "Casa 5", "Casa 9", "Casa 11"], answer: 2 },
{ question: "¿Qué casa está asociada con los amigos y grupos?", options: ["Casa 8", "Casa 11", "Casa 4", "Casa 2"], answer: 1 },
{ question: "¿Qué planeta rige la transformación profunda?", options: ["Plutón", "Marte", "Venus", "Saturno"], answer: 0 },
{ question: "¿Qué signo está asociado con la nutrición y el hogar?", options: ["Cáncer", "Libra", "Virgo", "Sagitario"], answer: 0 },
{ question: "¿Qué planeta rige las emociones y el inconsciente?", options: ["La Luna", "Urano", "Mercurio", "Venus"], answer: 0 },
{ question: "¿Qué signo rige el liderazgo?", options: ["Aries", "Piscis", "Tauro", "Virgo"], answer: 0 },
{ question: "¿Cuál es el planeta del amor?", options: ["Venus", "Júpiter", "Marte", "Neptuno"], answer: 0 },
{ question: "¿Qué signo se relaciona con la comunicación escrita y hablada?", options: ["Géminis", "Leo", "Escorpio", "Tauro"], answer: 0 },
{ question: "¿Qué signo representa el sacrificio y la compasión?", options: ["Capricornio", "Piscis", "Aries", "Leo"], answer: 1 },
{ question: "¿Qué planeta rige la acción y la energía?", options: ["Marte", "Saturno", "Júpiter", "Neptuno"], answer: 0 }];
