export const numerologyQuestions = [{ question: "¿Qué es la numerología?", options: ["Un sistema que interpreta vibraciones numéricas", "Un oráculo de cartas", "Un método astrológico", "Un sistema de meditación"], answer: 0 },
{ question: "¿Qué número representa liderazgo? y la individualidad", options: ["1", "2", "5", "7"], answer: 0 },
{ question: "¿Qué número simboliza cooperación y sensibilidad?", options: ["1", "2", "8", "9"], answer: 1 },
{ question: "El número 3 se asocia con:", options: ["Comunicación", "Soledad", "Miedo", "Oscuridad"], answer: 0 },
{ question: "El número 4 representa:", options: ["Disciplina y estructura", "Libertad", "Espiritualidad", "Caos"], answer: 0 },
{ question: "El número 5 vibra con:", options: ["Cambio", "Control", "Soledad", "Apego"], answer: 0 },
{ question: "El número 6 se relaciona con:", options: ["Familia", "Agresión", "Suerte", "Miedo"], answer: 0 },
{ question: "El número 7 vibra con:", options: ["Espiritualidad", "Pereza", "Impulsividad", "Furia"], answer: 0 },
{ question: "El número 8 simboliza:", options: ["Poder material", "Romance", "Soledad", "Creatividad"], answer: 0 },
{ question: "El número 9 representa:", options: ["Cierre y compasión", "Arrogancia", "Miedo", "Negación"], answer: 0 },
{ question: "¿Qué número se calcula con la fecha de nacimiento completa?", options: ["Número del alma", "Número de destino", "Número oculto", "Número de personalidad"], answer: 1 },
{ question: "¿Qué número se obtiene de las vocales del nombre?", options: ["Número del alma", "Número de destino", "Número de sombra", "Número maestro"], answer: 0 },
{ question: "¿Qué número se obtiene de las consonantes del nombre?", options: ["Número de personalidad", "Número del alma", "Número de destino", "Número cósmico"], answer: 0 },
{ question: "El número maestro 11 vibra con:", options: ["Intuición elevada", "Ira", "Materialismo", "Negación"], answer: 0 },
{ question: "El número maestro 22 es conocido como:", options: ["Maestro sanador", "Maestro constructor", "Maestro espiritual", "Maestro iniciático"], answer: 1 },
{ question: "El número maestro 33 se relaciona con:", options: ["Servicio universal", "Control", "Oscuridad", "Engaño"], answer: 0 },
{ question: "El número 1 en sombra puede mostrar:", options: ["Ego excesivo", "Silencio", "Dispersión", "Apego"], answer: 0 },
{ question: "El número 2 en sombra puede mostrar:", options: ["Dependencia", "Orgullo", "Ira", "Aislamiento"], answer: 0 },
{ question: "El número 3 en sombra puede mostrar:", options: ["Dispersión", "Rigidez", "Apego", "Miedo"], answer: 0 },
{ question: "El número 4 en sombra puede mostrar:", options: ["Rigidez extrema", "Soñar demasiado", "Caos emocional", "Frialdad"], answer: 0 },
{ question: "El número 5 en sombra puede mostrar:", options: ["Excesos", "Control", "Furia", "Negación"], answer: 0 },
{ question: "El número 6 en sombra puede mostrar:", options: ["Control emocional", "Evasión", "Miedo", "Ira"], answer: 0 },
{ question: "El número 7 en sombra puede mostrar:", options: ["Aislamiento", "Apego", "Vanidad", "Frustración"], answer: 0 },
{ question: "El número 8 en sombra puede mostrar:", options: ["Abuso de poder", "Sensibilidad extrema", "Confusión", "Evasión"], answer: 0 },
{ question: "El número 9 en sombra puede mostrar:", options: ["Evitar cierres", "Apego", "Posesividad", "Rutina"], answer: 0 },
{ question: "El número karmático 13 representa:", options: ["Disciplina", "Furia", "Oscuridad", "Pasión"], answer: 0 },
{ question: "El número karmático 14 representa:", options: ["Exceso", "Control", "Poder", "Desesperanza"], answer: 0 },
{ question: "El número karmático 16 representa:", options: ["Caída del ego", "Abundancia", "Orgullo", "Rutina"], answer: 0 },
{ question: "El número karmático 19 representa:", options: ["Lecciones de ego", "Espiritualidad pura", "Renacimiento", "Rutina"], answer: 0 },
{ question: "¿Qué número inicia la mayoría de ciclos humanos?", options: ["1", "2", "7", "9"], answer: 0 },
{ question: "¿Cada cuántos años cambia un ciclo numerológico?", options: ["3", "7", "9", "11"], answer: 2 },
{ question: "El número 3 favorece:", options: ["Comunicación", "Soledad", "Arrogancia", "Rigidez"], answer: 0 },
{ question: "El número 4 favorece:", options: ["Estructura", "Caos", "Oscuridad", "Sueños"], answer: 0 },
{ question: "El número 5 favorece:", options: ["Cambio", "Miedo", "Rutina", "Negación"], answer: 0 },
{ question: "El número 7 favorece:", options: ["Introspección", "Pasión", "Caos", "Rutina"], answer: 0 },
{ question: "El número 8 favorece:", options: ["Poder material", "Evasión", "Silencio", "Inestabilidad"], answer: 0 },
{ question: "El número 9 favorece:", options: ["Cierre", "Inicio", "Confusión", "Rutina"], answer: 0 },
{ question: "¿Qué número se relaciona con la independencia?", options: ["1", "2", "6", "9"], answer: 0 },
{ question: "¿Qué número se relaciona con el servicio?", options: ["6", "8", "4", "5"], answer: 0 },
{ question: "¿Qué número vibra con la creatividad verbal?", options: ["3", "5", "7", "8"], answer: 0 },
{ question: "¿Qué número representa intuición?", options: ["7", "1", "4", "9"], answer: 0 },
{ question: "¿Cuál no es un número maestro?", options: ["11", "22", "33", "44"], answer: 3 },
{ question: "¿Cuál es el número de destino más común?", options: ["1", "4", "7", "9"], answer: 3 },
{ question: "¿Qué número es más compatible con el 1?", options: ["2", "7", "8", "9"], answer: 2 },
{ question: "¿Qué número es más compatible con el 2?", options: ["1", "4", "6", "9"], answer: 2 },
{ question: "¿Qué número es más compatible con el 3?", options: ["5", "7", "4", "9"], answer: 0 },
{ question: "¿Qué número es más compatible con el 4?", options: ["1", "6", "8", "9"], answer: 2 },
{ question: "¿Qué número es más compatible con el 5?", options: ["3", "7", "9", "2"], answer: 0 },
{ question: "¿Qué número es más compatible con el 6?", options: ["1", "2", "4", "9"], answer: 3 },
{ question: "¿Qué número es más compatible con el 7?", options: ["2", "3", "4", "9"], answer: 0 },
{ question: "¿Qué estudia principalmente la numerología?", options: ["El destino a través de símbolos gráficos","La influencia de los números en la vida","La astrología planetaria","La lectura del tarot"], answer: 1 },
  ];
